import Head from 'next/head';
import Image from 'next/image';
import { useScrollPosition } from '../hooks/useScrollPosition';
import Scrollspy from 'react-scrollspy';
import Navbar from '../components/Navbar';
import NavbarFixed from '../components/NavbarFixed';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';

export default function Home() {
	const scrollPos = useScrollPosition();

	return (
		<div>
			<NavbarFixed
				visibility={
					scrollPos
						? 'visible opacity-1'
						: 'invisible opacity-0 transition-opacity linear duration-500'
				}
			/>
			<Navbar />
			<Head>
				<title>Hideo Nishimura - Portfolio</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main />
			<About />
			<Skills />
			<Projects />
		</div>
	);
}
